In [ ]:
# Question 1

#create a list
numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# append()
numbers.append(60)
print("Original List:", numbers)

#extend()
numbers.extend([70, 80])
print("After exetend:", numbers)

# insert()
numbers.insert(2,27)
print("After insert:", numbers)

# remove()
numbers.remove(40)
print("After remove:", numbers)

#pop()
numbers.pop()
print("After p0p:", numbers)

# index()
print("Index of 30:", numbers.index(30))

# sort()
numbers.sort()
print("After sort:", numbers)

# reverse()
numbers.reverse()
print("After reverse:", numbers)

# clear()
numbers.clear()
print("After clear:", numbers)

Original List: [10, 20, 30, 40, 50]
Original List: [10, 20, 30, 40, 50, 60]
After exetend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 27, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 27, 30, 50, 60, 70, 80]
After p0p: [10, 20, 27, 30, 50, 60, 70]
Index of 30: 3
After sort: [10, 20, 27, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 27, 20, 10]
After clear: []


In [7]:
# Question-2
students = ("Rohan", "Alekhya", "Sherli")
print("Original Tuple:", students)
students[1] = "Sujatha"
print(students)

Original Tuple: ('Rohan', 'Alekhya', 'Sherli')


TypeError: 'tuple' object does not support item assignment

Tuple is immutable in python.
It does not allow changing, adding, or removing elements after it is created. 
Therefore, trying to change the second element results in:
TypeError: 'tuple' object doesnot support item assignment

In [9]:
# Question 3
numbers = {10, 20, 30, 40, 50, 20, 40, 30}
print("Set:", numbers)

Set: {50, 20, 40, 10, 30}


 Explanation: A set automatically removes duplicate values and stores only unique elements.
Sets are unordered, so the output order may be different each time.

In [10]:
# Question 4
student = {
    "name": "Alekhya",
    "age": 22,
    "city": "Hyderabad"
}
print("Original Dictionary:", student)

# Update age
student["age"] = 23

# Add a new key
student["email"] = "alekhya@gmail.com"

print("Updated Dictionary:", student)

Original Dictionary: {'name': 'Alekhya', 'age': 22, 'city': 'Hyderabad'}
Updated Dictionary: {'name': 'Alekhya', 'age': 23, 'city': 'Hyderabad', 'email': 'alekhya@gmail.com'}


In [12]:
# Question 5
age = 20
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [1]:
# Question 6
marks = 75
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B


In [2]:
# Question 7
number = 8
if number > 0:
    print("The number is positive.")
    if number % 2 == 0:
        print("The number is also even.")
    else:
        print("The number is odd.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is positive.
The number is also even.


In [5]:
 # Section-B: Numpy
# Question 8

import numpy as np
#Scalar
scalar = np.array(5)
print("Scalar:")
print(scalar)

# 1D Array
array1 = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(array1)

#2D Array
array2 = np.array([[10, 20, 30],
                  [40, 50, 60]])
print("\n2D Array:")
print(array2)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


In [6]:
# Question 9
import numpy as np
random_array = np.random.randint(0, 101, (4, 4))

print("4x4 Random Array:")
print(random_array)

4x4 Random Array:
[[66 70 53 99]
 [43 31 71 53]
 [26 78 41 89]
 [94  5 93 59]]


In [10]:
# Question 10
import numpy as np
import pandas as pd

#create a  3x3 Numpy array
array = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]
])

# convert to DataFrame
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
# Print the DataFrame
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


In [15]:
# Section-C Exploring Pandas
# Question-11
import pandas as pd
data = {
    "Name": ["Alekhya", "Rohan", "Sherli", "Sudeep", "Sujatha", 
             "Mamili", "Rahul", "vikram", "Gopini", "Alekhya"],

    "Age": [22, 23, 21, 22, 22, 
            24,25, 23, 22, 24],
    "City": ["Hyderabad", "Delhi", "Mumbai", "Chennai", "Pune",
             "Bangalore", "Hyderabad", "Delhi", "Mumbai", "Hyderabad"],
    "Salary": [35000, 42000, None, 38000, 45000,
               None, 4000, 39000, 46000, 35000]
}
df = pd.DataFrame(data)
print(df)


      Name  Age       City   Salary
0  Alekhya   22  Hyderabad  35000.0
1    Rohan   23      Delhi  42000.0
2   Sherli   21     Mumbai      NaN
3   Sudeep   22    Chennai  38000.0
4  Sujatha   22       Pune  45000.0
5   Mamili   24  Bangalore      NaN
6    Rahul   25  Hyderabad   4000.0
7   vikram   23      Delhi  39000.0
8   Gopini   22     Mumbai  46000.0
9  Alekhya   24  Hyderabad  35000.0
